### ISSUE TITLE
Fix Portgres OperationalError (hard to reproduce)

### ISSUE THREAD

**Issue by OPersian** [OPersian/url_shortener#10]
Fix Portgres OperationalError upon (very first?) devstack run.

**Environment**

- macOS Big Sur, Version 11.7
- Processor: 2,8 GHz Quad-Core Intel Core i7

**STR**

- build the devstack
```
sudo docker-compose -f docker-compose-dev.yml up
```
- run the app. ❗  I cannot reproduce the issue anymore on my macOS: I stopped the container and started it again, and the issue disappeared.
```
sudo docker-compose -f docker-compose-dev.yml up
```

**AB**

- the app is up and running, and API is useable e.g. with proper URL passed to /shorten_url/ (e.g. https://www.example1.com) , getting status 201.

**EB**

- getting OperationalError `django.db.utils.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused` (see the full traceback below).

**Traceback**
```
url_shortener             | The above exception was the direct cause of the following exception:
url_shortener             |
url_shortener             | Traceback (most recent call last):
url_shortener             |   File "/usr/src/app/manage.py", line 22, in <module>
url_shortener             |     main()
url_shortener             |   File "/usr/src/app/manage.py", line 18, in main
url_shortener             |     execute_from_command_line(sys.argv)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
url_shortener             |     utility.execute()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
url_shortener             |     self.fetch_command(subcommand).run_from_argv(self.argv)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
url_shortener             |     self.execute(*args, **cmd_options)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
url_shortener             |     output = self.handle(*args, **options)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
url_shortener             |     res = handle_func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 114, in handle
url_shortener             |     executor = MigrationExecutor(connection, self.migration_progress_callback)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
url_shortener             |     self.loader = MigrationLoader(self.connection)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
url_shortener             |     self.build_graph()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
url_shortener             |     self.applied_migrations = recorder.applied_migrations()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
url_shortener             |     if self.has_table():
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
url_shortener             |     with self.connection.cursor() as cursor:
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
url_shortener             |     return self._cursor()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
url_shortener             |     self.ensure_connection()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
url_shortener             |     with self.wrap_database_errors:
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
url_shortener             |     raise dj_exc_value.with_traceback(traceback) from exc_value
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
url_shortener             |     self.connect()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
url_shortener             |     self.connection = self.get_new_connection(conn_params)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
url_shortener             |     connection = Database.connect(**conn_params)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
url_shortener             |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
url_shortener             | django.db.utils.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
url_shortener             | 	Is the server running on that host and accepting TCP/IP connections?
```

**Comment by OPersian** [comment]
This issue never reproduced, on newer machines in particular (see characteristics in https://github.com/OPersian/url_shortener/issues/12)
