### ISSUE TITLE
Postgres OperationalError on newer macOS: ARM-X86_X64 Apple vs Intel

### ISSUE THREAD

**Issue by OPersian** [OPersian/url_shortener#12]
Upon build, getting Postgres-related OperationalError (full traceback presented below).

OS: macOS Ventura 13.0.1
Chip: Apple M1 Max

Solution:

1. update docker-compose indicating the platform: https://github.com/OPersian/url_shortener/commit/9fd5f893db9dfeaab6ef44e51c85b37d63032d52
2. update env variable on macOS `DOCKER_DEFAULT_PLATFORM=linux/amd64`: https://stackoverflow.com/a/69636473
3. run terminal with `rosetta` https://apple.stackexchange.com/a/428769
4. build the app
 

Full traceback:

```
url_shortener             | Traceback (most recent call last):
url_shortener             |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
url_shortener             |     self.run()
url_shortener             |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
url_shortener             |     self._target(*self._args, **self._kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
url_shortener             |     fn(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
url_shortener             |     self.check_migrations()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 564, in check_migrations
url_shortener             |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
url_shortener             |     self.loader = MigrationLoader(self.connection)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
url_shortener             |     self.build_graph()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
url_shortener             |     self.applied_migrations = recorder.applied_migrations()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
url_shortener             |     if self.has_table():
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
url_shortener             |     with self.connection.cursor() as cursor:
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
url_shortener             |     return self._cursor()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
url_shortener             |     self.ensure_connection()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
url_shortener             |     with self.wrap_database_errors:
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
url_shortener             |     raise dj_exc_value.with_traceback(traceback) from exc_value
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
url_shortener             |     self.connect()
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
url_shortener             |     self.connection = self.get_new_connection(conn_params)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
url_shortener             |     return func(*args, **kwargs)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
url_shortener             |     connection = Database.connect(**conn_params)
url_shortener             |   File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
url_shortener             |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
url_shortener             | django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above
```

**Comment by OPersian** [comment]
Code fix: https://github.com/OPersian/url_shortener/commit/9fd5f893db9dfeaab6ef44e51c85b37d63032d52

Env updates also required (see "Solution" in the issue description).
